### ISSUE TITLE
Table: mover.damage_scale listed as 'dm_scale' in the documentation

### ISSUE THREAD

**Issue by MamadioCMCC** [GFDRR/rdl-doc#4]
https://gfdrr.github.io/rdl-doc/vulnerability.html#table-moverdm_scale

Inconsistent reference to contribution datetime.
In the Loss schema: contribution.contributed_at
In the vulnerability schema: f_core.created_at

**Comment by ConnectedSystems** [comment]
I think this one is no longer relevant as the vulnerability schema now has its own contribution table

**Comment by stufraser1** [comment]
Yes we'll need to remove any other now-duplicated fields

**Comment by MamadioCMCC** [comment]
- moved contribution table to common, removed from subschemas. Second field became general "set_id"
- removed "created at" field from   V schema f.core table
Closing
