### ISSUE TITLE
Change URL to match

### ISSUE THREAD

**Issue by ConnectedSystems** [GFDRR/rdl-doc#9]
Minor pedantic change request.

Add "s" to "doc". in doc.riskdatalibrary.org

"Docs" is the usual parlance used to refer to documentation (as it is a set of documents)

See for example: 
- https://**docs**.microsoft.com/
- https://www.mk**docs**.org/

**Comment by pzwsk** [comment]
Done in DNS and Github settings, please allow few min to update.
